ktor {
    deployment {
        port = 3345
        port = ${?PORT}
        host = "127.0.0.1"
        host = ${?HOST}
    }

    application {
        modules = [ ru.alcoserver.ApplicationKt.configureServer ]
    }
}

google {
    cloud {
        project-number = 929390260810
        project-number = ${?GOOGLE_CLOUD_PROJECT_NUMBER}
    }
}

firebase {
    config {
        path = "config/firebase-service-account.json"
        path = ${?FIREBASE_CONFIG_PATH}
    }
}

include "application.local.conf"

yookassa {
    shop-id = ${?YOOKASSA_SHOP_ID}
    secret-key = ${?YOOKASSA_SECRET_KEY}
    client-public-key = ${?YOOKASSA_CLIENT_PUBLIC_KEY}
}
