ktor {
    deployment {
        port = 3344
        port = ${?PORT}
        host = "0.0.0.0"
        host = ${?HOST}
    }

    application {
        modules = [ ru.alcoserver.ApplicationKt.configureServer ]
    }
}

google {
    cloud {
        project-number = 929390260810
        project-number = ${?GOOGLE_CLOUD_PROJECT_NUMBER}
    }
}

firebase {
    config {
        path = "config/firebase-service-account.json"
        path = ${?FIREBASE_CONFIG_PATH}
    }
}
